### ISSUE TITLE
Register Extensions manner/syntax on the Asciidoctor.js docmentation seems to be updated

### ISSUE THREAD

**Issue by ken-okabe** [oncletom/asciidoctor-extension-interactive-runner#7]
Hi, thanks for the nice extension.

[Register Extensions](https://asciidoctor-docs.netlify.com/asciidoctor.js/extend/extensions/register/) manner/syntax on the Asciidoctor.js docmentation seems to be updated;

https://asciidoctor-docs.netlify.com/asciidoctor.js/extend/extensions/tree-processor/

and, the npm module and the Usage example looks incompatible to the official instruction.

I tried to modify by myself, and pull-request, but for some reason, it does not work so far, so I would like request to update to the compatible extenstion to the latest version of  Asciidoctor.js.

Thanks!!

**Comment by yannschepens** [comment]
Hi, it won't work as it with Antora, the process method is not called for DocinfoProcessor (https://gitlab.com/antora/antora/issues/438).
